# Generated by Django 4.2.7 on 2023-11-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_manager_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='informationcomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='note',
            name='informationcomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='informationcomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='informationcomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='informationcomponent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='informationcomponent',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='componentlink',
            name='from_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_links', to='information_manager_base.informationcomponent'),
        ),
        migrations.AddField(
            model_name='componentlink',
            name='to_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_links', to='information_manager_base.informationcomponent'),
        ),
        migrations.AddField(
            model_name='informationcomponent',
            name='linked_components',
            field=models.ManyToManyField(related_name='linked_to', through='information_manager_base.ComponentLink', to='information_manager_base.informationcomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='componentlink',
            unique_together={('from_component', 'to_component')},
        ),
    ]
